<e> ::= max{<op1>}+<op2>|
        max{<op1>}+0.<c><c>*<op2>|
        max{<op1>}-<op2>|
        max{<op1>}-0.<c><c>*<op2>|
        max{<op1>}*<op2>|
        max{<op1>}*0.<c><c>*<op2>|
        max{<op1>}/<op2>|
        max{<op1>}/0.<c><c>*<op2>|
        max{<op1>}|
        max{x[i]/y}

<op1>     ::=   <optional_var>+<op1>|
                <op1>+<op1>|
                <optional_var>-<op1>|
                <op1>-<optional_var>|
                <op1>-<op1>|
                <optional_var>*<op1>|
                <op1>*<op1>|
                <optional_var>/<op1>|
                <op1>/<optional_var>|
                <op1>/<op1>|
                sqrt(<op1>)|
                <needed_var>

<op2>      ::=  <op2>+<op2>|
                <op2>-<op2>|
                <op2>*<op2>|
                <op2>/<op2>|
                sqrt(<op2>)|
                <optional_var>

<needed_var>    ::= x[i]|y|x[i]/y
<optional_var>  ::= x_sum|x_avg|x_max|x_min|<c><c>.<c><c>|0.<c><c>
<c>  ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
